[phases.setup]
cmds = [
  'echo "upload_max_filesize=10M;" >> /nix/store/7qvqslx4fpz7qwgbd9091lgcs708b4gg-php-with-extensions-8.1.29/lib/php.ini',
  'echo "post_max_size=10M;" >> /nix/store/7qvqslx4fpz7qwgbd9091lgcs708b4gg-php-with-extensions-8.1.29/lib/php.ini'
]